"""Stable Chinese terrain names sourced from the local War Thunder client."""

from __future__ import annotations

from collections.abc import Mapping

# Source: local War Thunder lang.vromfs.bin, represented by the matching
# War-Thunder-Datamine 2.57.1.65 extraction, lang/missions_locations.csv,
# simplified-Chinese <Chinese> column. Zero-width layout characters are
# intentionally removed before the names are used for catalog generation.
# The Launcher keeps this table only as a backward-compatible fallback for
# catalogs published before the signed display_name_zh field existed.
WAR_THUNDER_CLIENT_TERRAIN_NAMES_ZH: Mapping[str, str] = {
    "air_afghan": "阿富汗",
    "air_africa_desert": "阿拉曼",
    "air_archipelago": "热带海岸",
    "air_denmark": "丹麦",
    "air_equatorial_island": "波旁岛",
    "air_falklands": "马尔维纳斯 (福克兰) 群岛",
    "air_grand_canyon": "落基峡谷",
    "air_israel": "戈兰高地",
    "air_kamchatka": "焚风山谷",
    "air_ladoga": "拉多加",
    "air_mysterious_valley": "幽邃峡谷",
    "air_pyrenees": "山间峡谷",
    "air_race_phiphi_islands": "披披群岛",
    "air_skyscraper_city": "大都会",
    "air_smolensk": "斯摩棱斯克",
    "air_south_eastern_city": "东南渔湾",
    "air_southeastern_cliffs": "擎天石柱",
    "air_vietnam": "越南",
    "arcade_africa_canyon": "非洲峡谷",
    "arcade_africa_seashore": "沙漠海岸",
    "arcade_alps": "阿尔卑斯牧场",
    "arcade_asia_4roads": "雅鲁藏布大峡谷",
    "arcade_canyon_snow": "铁矿区",
    "arcade_ireland": "爱尔兰",
    "arcade_mediterranean": "希腊",
    "arcade_norway_fjords": "北欧峡湾",
    "arcade_norway_green": "挪威 • 绿色山脊",
    "arcade_norway_plain": "挪威 • 山麓",
    "arcade_phiphi_crater": "披披群岛 • 火山湖",
    "arcade_phiphi_crater_rocks": "披披群岛 • 秘密基地",
    "arcade_rice_terraces": "丰收梯田",
    "arcade_snow_rocks": "世界之巅",
    "arcade_tabletop_mountain": "圭亚那高原",
    "arcade_zhang_park": "张家界峭壁群峰",
    "avg_abandoned_factory": "废弃工厂",
    "avg_abandoned_town": "山野荒城",
    "avg_africa_desert": "阿拉曼",
    "avg_alaska_town": "阿拉斯加 • 都市丛林",
    "avg_american_valley": "美国 • 沙漠之城",
    "avg_aral_sea": "咸海",
    "avg_arctic": "极北之地",
    "avg_ardennes": "突出部 - 陆战",
    "avg_berlin": "柏林 - 陆战",
    "avg_breslau": "布雷斯劳",
    "avg_container_port": "货运港口",
    "avg_eastern_europe": "东欧",
    "avg_egypt_sinai": "西奈半岛",
    "avg_european_fortress": "白石要塞",
    "avg_finland": "芬兰",
    "avg_fulda": "富尔达缺口",
    "avg_greece": "阿提卡",
    "avg_guadalcanal": "瓜达尔卡纳尔岛 - 陆战",
    "avg_hurtgen": "许特根森林",
    "avg_iberian_castle": "伊比利亚古堡",
    "avg_ireland": "爱尔兰 • 灰烬之川",
    "avg_israel": "日耀之城",
    "avg_japan": "日本 • 皇家庭园",
    "avg_karelia_forest_a": "卡累利阿",
    "avg_karpaty_passage": "喀尔巴阡山",
    "avg_korea_lake": "朝鲜 • 三八线",
    "avg_krymsk": "库班 - 陆战",
    "avg_kursk_villages": "库尔斯克 • 炽烈之径",
    "avg_lazzaro_italy_new_city": "坎帕尼亚",
    "avg_mozdok": "莫兹多克 - 陆战",
    "avg_netherlands": "北荷兰省",
    "avg_normandy": "诺曼底",
    "avg_northern_india": "山麓之邦",
    "avg_northern_valley": "黄金矿场",
    "avg_nuclear_incident": "阿拉斯加 • 核爆原点",
    "avg_poland": "波兰",
    "avg_port_novorossiysk": "新罗西斯克",
    "avg_red_desert": "红色沙漠",
    "avg_rheinland": "莱茵河畔",
    "avg_sector_montmedy": "马其诺防线",
    "avg_sector_montmedy_snow": "马其诺防线",
    "avg_snow_alps": "阿尔卑斯 • 冰风谷",
    "avg_soviet_range": "2271 号测试基地",
    "avg_soviet_suburban": "谢韦尔斯克-13",
    "avg_stalingrad_factory": "斯大林格勒 - 陆战",
    "avg_sweden": "瑞典",
    "avg_syria": "中东",
    "avg_training_ground": "靶场",
    "avg_tunisia_desert": "突尼斯",
    "avg_vietnam_hills": "越南 • 高地",
    "avg_vlaanderen": "佛兰德斯",
    "avg_volokolamsk": "沃洛科拉姆斯克",
    "avg_western_europe": "航天港",
    "avn_aleutian_islands": "阿留申群岛",
    "avn_alps_fjord": "苍翠山湾",
    "avn_bering_sea": "白令海",
    "avn_fiji": "斐济",
    "avn_finland_islands": "南克瓦尔肯海峡",
    "avn_franz_josef_land": "法兰士约瑟夫地群岛",
    "avn_japan": "日本 • 横滨港",
    "avn_new_zeland_cape": "新西兰 • 纷争海角",
    "avn_northwestern_islands": "维堡湾",
    "avn_norway_islands": "挪威群岛",
    "avn_peleliu": "帕劳群岛",
    "avn_san_francisco": "黄金海湾",
    "avn_south_africa": "南非",
    "avn_sunken_city": "沉没之城",
    "avn_volcanic_island": "火山岛",
    "berlin": "柏林",
    "britain": "不列颠",
    "bulge": "突出部",
    "caribbean_islands": "加勒比群岛",
    "dover_strait": "多佛海峡",
    "firing_range": "训练基地",
    "guadalcanal": "瓜达尔卡纳尔岛",
    "guam": "关岛",
    "honolulu": "瓦胡岛",
    "hurtgen": "许特根森林",
    "iwo_jima": "硫磺岛",
    "khalkhin_gol": "诺门罕",
    "korea": "朝鲜",
    "korsun": "科尔孙",
    "krymsk": "库班",
    "kursk": "库尔斯克",
    "malta": "马耳他",
    "midway": "中途岛",
    "moscow": "莫斯科",
    "mozdok": "莫兹多克",
    "mozdok_winter": "莫兹多克 • 冬季",
    "norway": "挪威",
    "peleliu": "贝里琉岛",
    "port_moresby": "莫尔兹比港",
    "ruhr": "鲁尔",
    "saipan": "塞班岛",
    "sector_montmedy": "马其诺防线",
    "sicily": "西西里",
    "spain": "西班牙",
    "stalingrad": "斯大林格勒",
    "stalingrad_w": "斯大林格勒 • 冬季",
    "tunisia": "突尼斯",
    "wake_island": "威克岛",
    "water": "太平洋",
    "zhengzhou": "郑州",
}

# These terrain artifact IDs are not present in the current client location
# table. Keep a readable fallback, but do not present it as client-sourced.
TERRAIN_NAME_FALLBACKS_ZH: Mapping[str, str] = {
    "air_normandy": "诺曼底",
    "avg_ardennes_snow": "阿登 • 雪地",
    "avg_football_field": "足球场",
    "avg_karantan": "卡兰坦",
    "avg_maginot_rework": "马其诺防线 • 重制版",
    "avg_poland_snow": "波兰 • 雪地",
    "avg_soviet_suburban_snow": "苏联郊区 • 雪地",
    "avn_africa_gulf": "非洲海湾",
    "avn_arabian_north_coast": "阿拉伯北部海岸",
    "avn_blacksea_port": "黑海港口",
    "avn_coral_islands": "珊瑚群岛",
    "avn_england_shore": "英格兰海岸",
    "avn_fuego_islands": "火地群岛",
    "avn_ice_port": "冰港",
    "avn_ireland_bay": "爱尔兰湾",
    "avn_mediterranean_port": "地中海港口",
    "avn_north_sea": "北海",
    "avn_phang_nga_bay_islands": "攀牙湾群岛",
    "hangar_field": "机库场地",
    "hangar_field_premium": "机库场地 • 高级",
}

TERRAIN_MAP_NAMES_ZH: Mapping[str, str] = {
    **WAR_THUNDER_CLIENT_TERRAIN_NAMES_ZH,
    **TERRAIN_NAME_FALLBACKS_ZH,
}

CLIENT_TERRAIN_NAME_IDS = frozenset(WAR_THUNDER_CLIENT_TERRAIN_NAMES_ZH)


def terrain_map_localized_name(map_id: object) -> str | None:
    """Return a bundled Chinese name when one is available."""

    value = str(map_id or "").strip()
    return TERRAIN_MAP_NAMES_ZH.get(value)


__all__ = [
    "CLIENT_TERRAIN_NAME_IDS",
    "TERRAIN_MAP_NAMES_ZH",
    "TERRAIN_NAME_FALLBACKS_ZH",
    "WAR_THUNDER_CLIENT_TERRAIN_NAMES_ZH",
    "terrain_map_localized_name",
]
