[CmdletBinding()]
param([switch]$Check)

$ErrorActionPreference = "Stop"
$repoRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot ".."))
$iconPath = Join-Path $repoRoot "bomana\assets\branding\app.ico"
$outputPath = Join-Path $repoRoot "native\telemetry_gateway\classic_icon_windows_generated.go"
$resourcePath = Join-Path $repoRoot "native\telemetry_gateway\rsrc_windows_amd64.syso"
$resourceHashPath = Join-Path $repoRoot "native\telemetry_gateway\rsrc_windows_amd64.sha256"
$manifestPath = Join-Path $repoRoot "native\telemetry_gateway\bridge_windows.manifest"
$bytes = [IO.File]::ReadAllBytes($iconPath)
if ($bytes.Length -lt 22 -or [BitConverter]::ToUInt16($bytes, 0) -ne 0 -or [BitConverter]::ToUInt16($bytes, 2) -ne 1) {
    throw "Classic Bomana icon is not a valid ICO file: $iconPath"
}

$count = [BitConverter]::ToUInt16($bytes, 4)
$entries = for ($index = 0; $index -lt $count; $index++) {
    $offset = 6 + 16 * $index
    $width = if ($bytes[$offset] -eq 0) { 256 } else { [int]$bytes[$offset] }
    $height = if ($bytes[$offset + 1] -eq 0) { 256 } else { [int]$bytes[$offset + 1] }
    [pscustomobject]@{
        Width = $width
        Height = $height
        Bits = [BitConverter]::ToUInt16($bytes, $offset + 6)
        Size = [BitConverter]::ToUInt32($bytes, $offset + 8)
        Offset = [BitConverter]::ToUInt32($bytes, $offset + 12)
    }
}
$selected = $entries | Where-Object { $_.Width -eq 32 -and $_.Height -eq 32 } | Sort-Object Bits -Descending | Select-Object -First 1
if (-not $selected -or $selected.Offset + $selected.Size -gt $bytes.Length) {
    throw "Classic Bomana ICO does not contain a valid 32x32 image"
}
$payload = [byte[]]::new($selected.Size)
[Array]::Copy($bytes, $selected.Offset, $payload, 0, $selected.Size)
$sourceHash = (Get-FileHash -LiteralPath $iconPath -Algorithm SHA256).Hash.ToLowerInvariant()
$payloadHash = [Convert]::ToHexString([Security.Cryptography.SHA256]::HashData($payload)).ToLowerInvariant()
$encoded = [Convert]::ToBase64String($payload)
$content = @"
// Code generated by tools/generate_bridge_icon.ps1 from bomana/assets/branding/app.ico; DO NOT EDIT.
//go:build windows

package main

const classicBomanaIconSourceSHA256 = "$sourceHash"
const classicBomanaIconPayloadSHA256 = "$payloadHash"
const classicBomanaIconBase64 = "$encoded"
"@.Replace("`r`n", "`n")
if ($Check) {
    if (-not (Test-Path -LiteralPath $outputPath) -or [IO.File]::ReadAllText($outputPath) -ne $content) {
        throw "Generated Bridge tray icon is stale; run tools/generate_bridge_icon.ps1"
    }
    if (-not (Test-Path -LiteralPath $resourcePath) -or (Get-Item -LiteralPath $resourcePath).Length -lt 512) {
        throw "Generated Bridge application icon resource is missing; run tools/generate_bridge_icon.ps1"
    }
    $declaredResourceHash = if (Test-Path -LiteralPath $resourceHashPath) { [IO.File]::ReadAllText($resourceHashPath).Trim() } else { "" }
    $actualResourceHash = (Get-FileHash -LiteralPath $resourcePath -Algorithm SHA256).Hash.ToLowerInvariant()
    if ($declaredResourceHash -ne $actualResourceHash) {
        throw "Generated Bridge application icon resource hash is stale; run tools/generate_bridge_icon.ps1"
    }
    return
}
[IO.File]::WriteAllText($outputPath, $content, [Text.UTF8Encoding]::new($false))
& go run github.com/akavel/rsrc@v0.10.2 -arch amd64 -ico $iconPath -manifest $manifestPath -o $resourcePath
if ($LASTEXITCODE -ne 0) { throw "Failed to generate Bridge Windows application icon resource" }
$resourceHash = (Get-FileHash -LiteralPath $resourcePath -Algorithm SHA256).Hash.ToLowerInvariant()
[IO.File]::WriteAllText($resourceHashPath, "$resourceHash`n", [Text.UTF8Encoding]::new($false))
